apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-canary
  namespace: argocd

spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: canary

  template:
    metadata:
      name: '{{metadata.labels.cluster}}-myapp'

    spec:
      project: default

      source:
        repoURL: https://github.com/gorin-lab/fleet
        targetRevision: main
        path: apps/myapp/overlays/{{metadata.labels.env}}

      destination:
        server: '{{server}}'
        namespace: myapp

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

